services:
  anydb-studio:
    build: .
    image: node:20-alpine
    container_name: anydb-studio
    ports:
      - 5173:5173
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - default

networks:
  default:
    driver: bridge
